### ISSUE TITLE
The organizer's e-mail changes the @ to %40

### ISSUE THREAD

**Issue by xCamacho91** [markuspoerschke/iCal#434] opened 2022-07-08 08:34 UTC
When the organizer's email is set and after urlencode($this->emailAddress) it is turning the @ into %40, do you have any way around this?

**Comment by JorisDebonnet** [comment] 2022-09-29 10:45
I also had this issue. It also happens with the new Attendees feature. 

The problem is the EmailAddress:toUri method which replaces the @ by %40.

I temporarily "fixed" this by simply replacing %40 back to @ in my final output, but of course that's not ideal. Perhaps when I have more time I'll create a PR, although anyone else also could.

**Comment by markuspoerschke** [comment] 2022-12-23 11:23
Thanks for raising this issue.

This bug will be fixed in https://github.com/markuspoerschke/iCal/pull/479.

**Closed as completed by markuspoerschke** 2022-12-23 11:23 UTC
