### ISSUE TITLE
Quoting of BYDAY inside RRULE when there is a ',' inside the string

### ISSUE THREAD

**Issue by hawkeyevc** [markuspoerschke/iCal#108] opened 2018-01-16 15:43 UTC
Hello 
I think that the escaping with `"´ of multiple days inside the BYDAY parameter is against the RFC. 
Example: 
RRULE:FREQ=WEEKLY;INTERVAL=1;UNTIL=20181231T235959Z;BYDAY="MO,TU,WE,TH,FR"
this will work correctly with some importer. I mentioned problems with Thunderbird Lightning and android.

correct is this:
RRULE:FREQ=WEEKLY;INTERVAL=1;UNTIL=20181231T235959Z;BYDAY=MO,TU,WE,TH,FR

I commented the Lines 94-96 out inside the \Eluceo\iCal\ParameterBag.php, but don't know if this will produce problems in other cases. For me this is the 'solution' for my problems.

**Comment by markuspoerschke** [comment] 2018-01-17 14:45
Commenting the quoting as you did will affect all kind of properties of the component. This might cause some problems when quoting is needed for other components.

The problem is that the Weekdays are passed as a string in https://github.com/markuspoerschke/iCal/blob/master/src/Property/Event/RecurrenceRule.php#L155. Rather than using the normal Parameter a ArrayParameter needs to be used.

I will check if I can fix this.

**Comment by markuspoerschke** [comment] 2018-01-17 14:53
I will close this in favor of #105. (Duplicate ticket)

**Closed by markuspoerschke** 2018-01-17 14:53 UTC
Labels: bug
